openapi: '3.0.0'
info:
  version: 2.3.0
  title: TODO
  description: Documentação da API do TODO
servers:
  - description: Development
    url: http://localhost:3000
  - description: Homolog
    url: TODO
  - description: Production
    url: TODO

paths:
  /pokemons/:pokemon_name:
    $ref: './paths/pokemon/listPokemon.yml'

security:
  - apiToken: []

